echo "-----------------------------------------------------------------------------------------------------"
echo "      Lista de comandos"
echo "-----------------------------------------------------------------------------------------------------"
echo "ayuda         ->      muestra comandos"
echo "buscar        ->      buscar un archivo en un directorio (carpeta a buscar , archivo que va a buscar)"
echo "creditos      ->      muestra creditos de los creadores"
echo "fecha         ->      muestra la fecha y hora"
echo "infosis       ->      muestra informacion del sistema"
echo "ahorcado      ->      pasar un buen rato jugando ahorcado"
echo "mp3Player     ->      reproductor de musica"
echo "Salir         ->      salir de la terminal"